source 'https://github.com/CocoaPods/Specs.git'

target 'PBTinyAlert', :exclusive => true do
  pod "PBTinyAlert", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "PBTinyAlert", :path => "../"

  
end
